# Generated by Django 5.0.4 on 2024-06-18 00:00

import apps.gallery.models
import apps.personnel.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('family', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='سمت')),
                ('mobile_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('image_name', models.ImageField(blank=True, null=True, upload_to=apps.gallery.models.FileUpload.upload_to, verbose_name='تصویر پروفایل')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان ثبت')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیر فعال')),
            ],
        ),
    ]
