# Generated by Django 5.0.4 on 2024-06-21 22:22

import apps.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name_plural': 'کارکنان'},
        ),
        migrations.AlterField(
            model_name='personnel',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=apps.gallery.models.FileUpload.upload_to, verbose_name='تصویر پروفایل'),
        ),
    ]
