# Generated by Django 5.0.4 on 2024-06-28 17:23

import apps.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_personnel_options_alter_personnel_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=apps.gallery.models.FileUpload.upload_to, verbose_name='تصویر پروفایل'),
        ),
    ]
