# Generated by Django 5.0.4 on 2024-04-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='dete_time',
            new_name='date_time',
        ),
    ]
