# Generated by Django 5.0.4 on 2024-04-14 23:02

import apps.memories.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_title', models.CharField(max_length=200, verbose_name='عنوان خاطره')),
                ('memory_text', models.TextField(verbose_name='متن خاطره')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان ثبت')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیر فعال')),
                ('user_registered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'verbose_name': 'خاطره',
                'verbose_name_plural': 'خاطره ها',
            },
        ),
        migrations.CreateModel(
            name='MemoryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_image_name', models.ImageField(upload_to=apps.memories.models.upload_gallery_image, verbose_name='تصویر خاطره')),
                ('memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memories.memory')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memories.memory')),
                ('user_like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
