# Generated by Django 5.0.4 on 2024-04-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorylike',
            old_name='user_like',
            new_name='user_liked',
        ),
    ]
