# Generated by Django 5.0.4 on 2024-04-06 23:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='نام مکان')),
                ('information', models.TextField(default='توضیحات', verbose_name='توضیحات')),
                ('place_image_name', models.ImageField(upload_to='images/places/', verbose_name='تصویر')),
                ('visiting_day', models.CharField(max_length=100, verbose_name='روزهای بازدید')),
                ('visiting_hour', models.CharField(max_length=100, verbose_name='ساعت بازدید')),
                ('rules', models.TextField(verbose_name='قوانین و مقررات')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان ثبت')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکانها',
                'db_table': 't_places',
            },
        ),
        migrations.CreateModel(
            name='VisitorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='نام نوع بازدید کننده')),
            ],
            options={
                'verbose_name': 'نوع بازدید کننده',
                'verbose_name_plural': 'نوع بازدید کننده ها',
                'db_table': 't_visitor_type',
            },
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='بهای بلیط')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='مکان مورد نظر')),
                ('visitor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.visitortype', verbose_name='نوع بازدید کننده')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
                'db_table': 't_ticket_prices',
            },
        ),
    ]
