# Generated by Django 5.0.4 on 2024-06-28 17:23

import apps.gallery.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField(verbose_name='کد مکان')),
                ('title_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن عنوان')),
                ('image_name', models.ImageField(upload_to=apps.gallery.models.FileUpload.upload_to, verbose_name='تصویر اصلی')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('gallery_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries_child', to='gallery.gallery', verbose_name='والد تصویر')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'db_table': 't_gallery',
            },
        ),
        migrations.CreateModel(
            name='MuseumGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=apps.gallery.models.FileUpload.upload_to, verbose_name='تصویر مرتبط')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='gallery.gallery', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'db_table': 't_museum_gallery',
            },
        ),
    ]
