# Generated by Django 5.0.4 on 2024-06-28 18:29

import apps.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumgallery',
            name='title_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='متن عنوان'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_name',
            field=models.ImageField(upload_to=apps.gallery.models.FileUpload.upload_to, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='museumgallery',
            name='image_name',
            field=models.ImageField(upload_to=apps.gallery.models.FileUpload.upload_to, verbose_name='تصویر مرتبط'),
        ),
    ]
