# Generated by Django 5.0.4 on 2024-06-28 18:43

import apps.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_museumgallery_title_text_alter_gallery_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_name',
            field=models.ImageField(upload_to=apps.gallery.models.FileUpload.upload_to, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='museumgallery',
            name='image_name',
            field=models.ImageField(upload_to=apps.gallery.models.FileUpload.upload_to, verbose_name='تصویر مرتبط'),
        ),
    ]
